trigger:
  - main
  - features/*
  - acpt

pool:
  vmImage:  'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Node_Installation_build
        steps:
          - task: NodeTool@0
            inputs: 
              versionSpec: '10.x'
            displayName: 'Node Installation'
          - script: |
              npm install -g @angular/cli
              npm install
              ng build --prod
            displayName: 'npm install and build'
