trigger:
  - main
  - features/*
  - acpt

pool:
  vmImage:  'ubuntu-latest'

variables:
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)

stages:
  - stage: Build
    jobs:
      - job: Node_Installation_build
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
        steps:
          - task: NodeTool@0
            inputs: 
              versionSpec: '16.17.1'
            displayName: 'Node Installation'
          - script: |
              npm install -g @angular/cli@latest
              npm install
              ng build
            displayName: 'npm install and build'
  - stage: Build_Versioning
    jobs:
      - job: Build_Custom_Versioning
        steps: 
          - script: | 
              echo $(major)
              echo $(Build.SourceBranchName)
              echo $(Build.SourceBranch)  

